dweeter/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path('accounts/', include('allauth.urls')),
    path("", include(profiles_urls, namespace="profile"))
] 
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.urls import path
from .views import HomePage, PostDetailView, NewPost

app_name = "feed"

urlpatterns = [
    path("", HomePage.as_view(), name = "index"),
    path("<int:pk>/", PostDetailView.as_view(), name = "detail"),
    path("newpost/", NewPost.as_view(), name = "post")
    
]

profiles/urls.py
from django.urls import path
from .views import ProfileDetailView

app_name = "profiles"

urlpatterns = [
   path("user/<int:pk>/", ProfileDetailView.as_view(), name = 'detail'),
]

feed/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

followers/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError


User = get_user_model()

# Create your models here.
class Follower(models.Model):
    followed_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="followed_by"
    )
    
    following = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name = "following"
    )
    
    def clean(self):
        if self.following == self.followed_by:
            raise ValidationError("A user cannot follow him or herself!")
        
    def __str__(self):
        return f"{self.following} is being followed by {self.followed_by}"
    
class Meta:
    constraints = [
        models.UniqueConstraint(fields=['followed_by', 'following'], name = 'unique_following')
    ]
    

profiles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

User = get_user_model()
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        related_name = "profile"
    )
    image = ImageField(upload_to = "profiles")
    
    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=User) 
def create_user_profile(sender, instance,created, **kwargs):
    if created:
        Profile.objects.create(user=instance)     

useraccounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone

# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('date_joined', timezone.now())
        
        if not username:
            raise ValueError("The username field must be set")
        if not email:
            raise ValueError("The email field must be set")
        
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user
    
    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, email, password, **extra_fields)
    

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)    
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_superuser = models.BooleanField(default=False)
    
    objects = CustomUserManager()
    
    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

feed/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class HomePage(ListView):
    http_method_names = ['get']
    template_name = "homepage.html"
    model = Post
    queryset = Post.objects.all().order_by("-id")
    context_object_name = 'posts'
    
class PostDetailView(DetailView):
    http_method_names = ['get']
    template_name = "detail.html"
    model = Post
    context_object_name = "post"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['post'] = self.object
    #     return context
    
class NewPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "newpost.html"
    fields = ['text']
    login_url = reverse_lazy('account_login')
    success_url = "/"
    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

followers/views.py
from django.shortcuts import render

# Create your views here.

profiles/views.py
from django.views.generic import DetailView
from .models import Profile
from followers.models import Follower
from feed.models import Post
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your views here.

class ProfileDetailView(DetailView):
    http_method_names = ['get']
    template_name = "profile_detail.html"
    model = Profile
    context_object_name = "profile"
    
    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    
    
    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)
        profile = self.get_object()
        posts = Post.objects.filter(author=profile.user).count()
        context['posts'] = posts
        if self.request.user.is_authenticated:
            is_following = self.is_following(self.request.user, profile.user)
            context['you_follow'] = is_following
            
        return context
    
    def is_following(self, user, profile_user):
        try:
            following = Follower.objects.get(following=profile_user, followed_by=user)
            return True
        except Follower.DoesNotExist:
            return False
   
    

feed/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock%}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    
</head>
<body>
<!-- component -->
<script defer src="https://unpkg.com/alpinejs@3.10.2/dist/cdn.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />

<!-- page -->
<main class="min-h-screen w-full bg-gray-100 text-gray-700" x-data="layout">
    <!-- header page -->
    <header class="flex w-full items-center justify-between border-b-2 border-gray-200 bg-white p-2">
        <!-- logo -->
        <div class="flex items-center space-x-2">
            <button type="button" class="text-3xl" @click="asideOpen = !asideOpen"><i class="bx bx-menu"></i></button>
            <div>DWEETER</div>
        </div>

        <!-- button profile -->
        <div>
            <button type="button" @click="profileOpen = !profileOpen" @click.outside="profileOpen = false"
                class="h-9 w-9 overflow-hidden rounded-full">
                <img src="https://plchldr.co/i/40x40?bg=111111" alt="plchldr.co" />
            </button>

            <!-- dropdown profile -->
            <div class="absolute right-2 mt-1 w-48 divide-y divide-gray-200 rounded-md border border-gray-200 bg-white shadow-md"
                x-show="profileOpen" x-transition>
                <div class="flex items-center space-x-2 p-2">
                    <img src="https://plchldr.co/i/40x40?bg=111111" alt="plchldr.co" class="h-9 w-9 rounded-full" />
                    <div class="font-medium">Hafiz Haziq</div>
                </div>

                <div class="flex flex-col space-y-3 p-2">
                    <a href="{% comment "" %}{% url "profiles:detail" post.author.id%}{% endcomment %}" class="transition hover:text-blue-600">My Profile</a>
                    <a href="#" class="transition hover:text-blue-600">Edit Profile</a>
                    <a href="#" class="transition hover:text-blue-600">Settings</a>
                </div>

                <div class="p-2">
                    <button class="flex items-center space-x-2 transition hover:text-blue-600">
                        <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1">
                            </path>
                        </svg>
                        <div>Log Out</div>
                    </button>
                </div>
            </div>
        </div>
    </header>


    <div class="flex">
        <!-- aside -->
        <aside class="flex w-72 flex-col space-y-2 border-r-2 border-gray-200 bg-white p-2" style="height: 90.5vh"
            x-show="asideOpen">
            <a href="{% url "feed:index"%}" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="text-2xl"><i class="bx bx-home"></i></span>
                <span>Home</span>
            </a>
            
            <a href="{% url "feed:post"%}" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="text-2xl"><i class="bx bx-layer-plus"></i></span>
                <span>New Post</span>
                
            </a>
            
            {% if request.user.is_authenticated%}
            <a href="{% url "account_logout"%}" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="text-2xl"><i class="bx bx-log-out"></i></span>
                <span>Logout</span>
            </a>
            {% else %}
            <a href="{% url "account_login"%}" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="text-2xl"><i class="bx bx-log-in"></i></span>
                <span>Login</span>
            </a>
            {% endif%}
        </aside>

        <!-- main content page -->
        <div class="w-full p-4">
            {% block body%}{% endblock%}    
        </div>
    </div>
</main>

<script>
    document.addEventListener("alpine:init", () => {
        Alpine.data("layout", () => ({
            profileOpen: false,
            asideOpen: true,
        }));
    });

    
</script>

    
</body>
</html>

feed/templates/detail.html
{% extends "base.html"%}

{% block title%}DETAIL PAGE{% endblock%}


{% block body%}
{% load thumbnail%}
<!-- component -->
<!-- post card -->
<div class="flex bg-white shadow-lg rounded-lg mx-4 md:mx-auto my-50 max-w-md md:max-w-2xl "><!--horizantil margin is just for display-->
    <div class="flex items-start px-4 py-6">
      {% thumbnail post.author.profile.image "373x373" crop="center" as im%}
       <img class="w-12 h-12 rounded-full object-cover mr-4 shadow" src="{{im.url}}" height="{{im.height}}" alt="avatar">
       {% endthumbnail%}
       <div class="">
          <div class="flex items-center justify-between">
             <h2 class="text-lg font-semibold text-gray-900 -mt-1">{{post.author.username}}</h2>
             <small class="text-sm text-gray-700 offset-10">{{post.date}}</small>
          </div>
          <p class="mt-3 text-gray-700 text-sm">
             {{post.text}}
          </p>
          <div class="mt-4 flex items-center">
             <div class="flex mr-2 text-gray-700 text-sm mr-3">
                <svg fill="none" viewBox="0 0 24 24"  class="w-4 h-4 mr-1" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
                 </svg>
                <span>12</span>
             </div>
             <div class="flex mr-2 text-gray-700 text-sm mr-8">
                <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
                </svg>
                <span>8</span>
             </div>
             <div class="flex mr-2 text-gray-700 text-sm mr-4">
                <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
                 </svg>
                <span>share</span>
             </div>
          </div>
       </div>
    </div>
 </div>

{% endblock%}

feed/templates/homepage.html
{% extends 'base.html' %}
{% block title%}HOMEPAGE{% endblock%}


{% block body%}
{% load thumbnail%}
    {% for post in posts%}
<!-- component -->
<!-- post card -->
<div class="flex bg-white shadow-lg rounded-lg mx-4 md:mx-auto my-56 max-w-md md:max-w-2xl "><!--horizantil margin is just for display-->
    <div class="flex items-start px-4 py-6">
        {% thumbnail post.author.profile.image "373x373" crop="center" as im%}
       <img class="w-12 h-12 rounded-full object-cover mr-4 shadow" src="{{im.url}}" height="{{im.height}}" alt="avatar">
       {% endthumbnail%}
       <div class="">
          <div class="flex items-center justify-between">
            <a href="{% url "profiles:detail" post.author.id%}">
             <h2 class="text-lg font-semibold text-gray-900 -mt-1">{{post.author.username}}</h2>
            </a>
             <small class="text-sm text-gray-700 offset-10">{{post.date}}</small>
          </div>
          <p class="mt-3 text-gray-700 text-sm">
             {{post.text}}
             <a href="{% url "feed:detail" post.id%}">readmore</a>
          </p>
         
          <div class="mt-4 flex items-center">
             <div class="flex mr-2 text-gray-700 text-sm mr-3">
                <svg fill="none" viewBox="0 0 24 24"  class="w-4 h-4 mr-1" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
                 </svg>
                <span>12</span>
             </div>
             <div class="flex mr-2 text-gray-700 text-sm mr-8">
                <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
                </svg>
                <span>8</span>
             </div>
             <div class="flex mr-2 text-gray-700 text-sm mr-4">
                <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
                 </svg>
                <span>share</span>
             </div>
          </div>
       </div>
    </div>
 </div>


    {% endfor%}
{% endblock%}

feed/templates/newpost.html
{% extends "base.html"%}

{% block body%}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <div>
        <div class="my-3">
            <button class=" bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
                <span class="mr-2">New Post</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" viewBox="0 0 24 24">
                    <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
            </button>
        </div>
    </div>

</form>
{% endblock%}

profiles/templates/profile_detail.html

{% extends "base.html"%}


{% block title%}PROFILE PAGE{% endblock%}

{% block body%}
{% load static %}
{% load thumbnail%}
    <!-- component -->
<div class="bg-gray-200 font-sans h-screen w-full flex flex-row justify-center items-center">
    <div class="card w-96 mx-auto bg-white  shadow-xl hover:shadow">
        {% thumbnail profile.image "373x373" crop="center" as im%}
       <img class="w-32 mx-auto rounded-full -mt-20 border-8 border-white" src="{{im.url}}" height="{{im.height}}" alt="">
       {% endthumbnail%}
       <div class="text-center mt-2 text-3xl font-medium">{{profile.user.username}}</div>
       <div class="text-center font-normal text-lg">{{posts}} posts</div>
       <div class="px-6 text-center mt-2 font-light text-sm">
         {# TODO add url for bio editing and create field for profile customization.#}
        <p>
           Front end Developer, avid reader. Love to take a long walk, swim
         </p>
       </div>
       <div>
        {% if request.user.is_authenticated%}
            {% if request.user != profile.user%}
                {% if you_follow%}
                <div>
                  <div class="my-3">
                      <button class=" bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit" id="unfollow" onclick="dtFollower()">Unfollow</button>
                  </div>
              </div> 
               {% else%}
               <div>
                <div class="my-3">
                    <button class=" bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit" id="follow" onclick="dtFollower()">Follow</button>
                </div>
            </div> 
                {% endif %}
                
            {% else %}        
                <p>This is your own profile page!!!!</p>
            {% endif%} 
        {% endif%}
    </div>
      <hr class="mt-8">
      <div class="flex p-4">
        <div class="w-1/2 text-center">
           <span class="font-bold">1.8 k</span> Followers
        </div>
        <div class="w-0 border border-gray-300">
           
        </div>
        <div class="w-1/2 text-center">
           <span class="font-bold">2.0 k</span> Following
        </div>
        
      </div>
    </div>
  </div>
  <script src="{% static 'js/main.js' %}"></script>
{% endblock%}